apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spicedb.fullname" . }}-migration
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spicedb
    spec:
      serviceAccountName: {{ include "spicedb.serviceAccountName" . }}
      tolerations:
        - effect: NoSchedule
          key: eks.amazonaws.com/compute-type
          value: fargate
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - migrate
            - head
            {{- if .Values.datastore.awsIam.enabled }}
            - --datastore-credentials-provider-name=aws-iam
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if and (ne .Values.datastore.engine "memory") .Values.datastore.connection.uriSecretName }}
            - name: SPICEDB_DATASTORE_CONN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ required "'datastore.connection.uriSecretName' is required" .Values.datastore.connection.uriSecretName }}
                  key: uri
                  optional: false
            {{- end }}
            - name: SPICEDB_DATASTORE_ENGINE
              value: {{ .Values.datastore.engine }}
            - name: SPICEDB_LOG_LEVEL
              value: {{ .Values.logLevel }}
